In [1]:
import pandas as pd

# import datafile
filepath='../data/heart.csv'
df_heart=pd.read_csv(filepath)
df_heart.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,0
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,0
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,0
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,0
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,0

In [2]:
from N1 import Preprocessing,generate_preprocess_parameters

# define preprocess parameters 

# identify target column
target='target'

# identify multicategorical_features
multicategorical_features=['cp', 'restecg', 'slope', 'ca', 'thal']

# identify continous_features
continuous_features=['age', 'trestbps', 'chol', 'thalach', 'oldpeak']

# define which columns must be anonymized and k value
anonymiser_feature_columns=['age','sex']
anonymiser_k=30

# generate preprocess parameters dict
preprocess_parameters=generate_preprocess_parameters(target,multicategorical_features,continuous_features,anonymiser_feature_columns,anonymiser_k)

# run preprocessing 
d1=Preprocessing(df_heart,preprocess_parameters)

# print dataset anonymized
d1.dataset_anonymized.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,['34-54'],['0'],3,145,233,1,0,150,0,2.3,0,0,1,0
1,['34-54'],['0'],2,130,250,0,1,187,0,3.5,0,0,2,0
2,['34-54'],['0'],1,130,204,0,0,172,0,1.4,2,0,2,0
3,['34-54'],['0'],1,120,236,0,1,178,0,0.8,2,0,2,0
4,['34-54'],['0'],0,120,354,0,1,163,1,0.6,2,0,2,0

In [3]:
# check anonymization by column
d1.anonymized_columns['age'].sort_index()

           count
age
['29-46']     50
['34-54']     40
['47-54']     54
['55-59']     51
['55-76']     56
['60-77']     52

In [4]:
d1.anonymized_columns['sex']

       count
sex
['0']     96
['1']    207

In [ ]:
from N1 import Classification
from sklearn.neighbors import KNeighborsClassifier

# choose model classifier
knn = KNeighborsClassifier(n_neighbors=15,n_jobs=-1)

# run Classification with preprocess dataset and model classifier 
knn_clf=Classification(d1.dataset_preprocessed,knn)

# print results
knn_clf.results()

In [ ]:
# GRID SEARCH
from N1 import generate_gs_preprocess_parameters

# define permanent preprocess parameters
target='target'
multicategorical_features=['cp', 'restecg', 'slope', 'ca', 'thal']
continuous_features=['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
anonymiser_feature_columns=['age','sex']

# define grid-search preprocess parameters
gs_parameters={'anonymiser_k':[None,1,5,10,20,50,100,200,302]}

# generate preprocess parameters dict fro grid-search
gs_preprocess_parameters=generate_gs_preprocess_parameters(gs_parameters,target,multicategorical_features,continuous_features,
                                                           anonymiser_feature_columns)

In [ ]:
# GRID SEARCH
from N1 import GridSearch
from sklearn.neighbors import KNeighborsClassifier

# choose model classifier
knn = KNeighborsClassifier(n_neighbors=15,n_jobs=-1)

# run Grid Search with dataset, preprocess parameters and model classifier 
gs_knn=GridSearch(df_heart,gs_preprocess_parameters,knn)

# print results
gs_knn.results()

In [ ]:
gs_knn.plot_results_2()

In [ ]:
# GRID SEARCH
from N1 import GridSearch
from sklearn.tree import DecisionTreeClassifier

# choose model classifier
clf=DecisionTreeClassifier(max_depth=3)

# run Grid Search with preprocess parameters and model classifier 
gs_clf=GridSearch(df_heart,gs_preprocess_parameters,clf)

# print results
gs_clf.results()

In [ ]:
gs_clf.plot_results_2()

In [ ]:
# GRID SEARCH
from N1 import GridSearch
from sklearn.ensemble import RandomForestClassifier

# choose model classifier
rf_clf=RandomForestClassifier()

# run Grid Search with preprocess parameters and model classifier 
gs_rf_clf=GridSearch(df_heart,gs_preprocess_parameters,rf_clf)

# print results
gs_rf_clf.results()

In [ ]:
gs_rf_clf.plot_results_2()